Traceback (most recent call last):
  File "5.py", line 9, in <module>
    print(age[3])
IndexError: list index out of range
